language: java

jdk:
  - oraclejdk8

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.gradle

before_install:
  - chmod +x gradlew

script:
  - ./gradlew setupDecompWorkspace idea
  - ./gradlew clean build
